server:
  port: 8099

watchdog:
  interval-ms: 5000 #fréquence à laquelle le watchdog check
  timeout-ms: 1500 #temps max pour considérer un check comme “KO”
  retries: 3  #nombre de tentatives avant de déclarer DOWN
  restart-threshold: 1 # nombre de cycle avant de redemarrer
  restart-timeout-ms: 10000
  post-restart:
    initial-wait-ms: 2000      # délai initial juste après docker restart
    max-wait-ms: 15000         # fenêtre totale pendant laquelle on attend que /health remonte
    poll-interval-ms: 2000     # fréquence des re-checks /health
  instances:
    - name: core-one
      ip: 172.31.249.170
      sshUser: vm-operations-core
      sshPort: 22
      healthUrl: http://172.31.249.170:8080/actuator/health
      restartCommand: "docker restart core-operational-backend-amd64-logs"

    - name: core-two
      ip: 172.31.252.225
      sshUser: vm-operational-core-2
      sshPort: 22
      healthUrl: http://172.31.252.225:8080/actuator/health
      restartCommand: "docker restart core-operational-backend-amd64-logs"


management:
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  output:
    ansi:
      enabled: ALWAYS